#ifndef HELPERS_HPP
#define HELPERS_HPP

#include "PKHeX.hpp"

namespace CTRPluginFramework {
    // Enumeration to identify different games
    enum class GameName {None, X, Y, OmegaRuby, AlphaSapphire};

    // Enumeration to categorize game sets (XY vs ORAS)
    enum class GameSeries {None, XY, ORAS};

    // External variables to hold the current game and series
    extern GameName currGameName;
    extern GameSeries currGameSeries;

    // Returns kalosSet if currGameSeries is XY; otherwise, returns hoennSet
    template<typename T>
    T AutoGameSet(T kalosSet, T hoennSet) {
        return (currGameSeries == GameSeries::XY) ? kalosSet : hoennSet;
    }

    // Overloads for specific types using initializer lists
    vector<u32> AutoGameSet(initializer_list<u32> kalosSet, initializer_list<u32> hoennSet);
    vector<string> AutoGameSet(initializer_list<string> kalosSet, initializer_list<string> hoennSet);

    // Determines address based on the current game
    u32 AutoGame(u32 first, u32 second);
    string AutoGame(string first, string second);

    // Detects game and series based on title ID
    void DetectGame(u32 titleID);

    // Checks if the game version is supported
    bool IsUpdateSupported(u16 version);

    // External vector for storing battle offsets
    extern vector<u32> battleOffset;

    // Configures battle offsets based on the current game
    void SetBattleOffset();

    // Determines if the game is currently in a battle
    bool IfInBattle();

    // List of all the Pokemon
    static const char *speciesList[721] = {
        "Bulbasaur",
        "Ivysaur",
        "Venusaur",
        "Charmander",
        "Charmeleon",
        "Charizard",
        "Squirtle",
        "Wartortle",
        "Blastoise",
        "Caterpie",
        "Metapod",
        "Butterfree",
        "Weedle",
        "Kakuna",
        "Beedrill",
        "Pidgey",
        "Pidgeotto",
        "Pidgeot",
        "Rattata",
        "Raticate",
        "Spearow",
        "Fearow",
        "Ekans",
        "Arbok",
        "Pikachu",
        "Raichu",
        "Sandshrew",
        "Sandslash",
        "NidoranF",
        "Nidorina",
        "Nidoqueen",
        "NidoranM",
        "Nidorino",
        "Nidoking",
        "Clefairy",
        "Clefable",
        "Vulpix",
        "Ninetales",
        "Jigglypuff",
        "Wigglytuff",
        "Zubat",
        "Golbat",
        "Oddish",
        "Gloom",
        "Vileplume",
        "Paras",
        "Parasect",
        "Venonat",
        "Venomoth",
        "Diglett",
        "Dugtrio",
        "Meowth",
        "Persian",
        "Psyduck",
        "Golduck",
        "Mankey",
        "Primeape",
        "Growlithe",
        "Arcanine",
        "Poliwag",
        "Poliwhirl",
        "Poliwrath",
        "Abra",
        "Kadabra",
        "Alakazam",
        "Machop",
        "Machoke",
        "Machamp",
        "Bellsprout",
        "Weepinbell",
        "Victreebel",
        "Tentacool",
        "Tentacruel",
        "Geodude",
        "Graveler",
        "Golem",
        "Ponyta",
        "Rapidash",
        "Slowpoke",
        "Slowbro",
        "Magnemite",
        "Magneton",
        "Farfetchd",
        "Doduo",
        "Dodrio",
        "Seel",
        "Dewgong",
        "Grimer",
        "Muk",
        "Shellder",
        "Cloyster",
        "Gastly",
        "Haunter",
        "Gengar",
        "Onix",
        "Drowzee",
        "Hypno",
        "Krabby",
        "Kingler",
        "Voltorb",
        "Electrode",
        "Exeggcute",
        "Exeggutor",
        "Cubone",
        "Marowak",
        "Hitmonlee",
        "Hitmonchan",
        "Lickitung",
        "Koffing",
        "Weezing",
        "Rhyhorn",
        "Rhydon",
        "Chansey",
        "Tangela",
        "Kangaskhan",
        "Horsea",
        "Seadra",
        "Goldeen",
        "Seaking",
        "Staryu",
        "Starmie",
        "MrMime",
        "Scyther",
        "Jynx",
        "Electabuzz",
        "Magmar",
        "Pinsir",
        "Tauros",
        "Magikarp",
        "Gyarados",
        "Lapras",
        "Ditto",
        "Eevee",
        "Vaporeon",
        "Jolteon",
        "Flareon",
        "Porygon",
        "Omanyte",
        "Omastar",
        "Kabuto",
        "Kabutops",
        "Aerodactyl",
        "Snorlax",
        "Articuno",
        "Zapdos",
        "Moltres",
        "Dratini",
        "Dragonair",
        "Dragonite",
        "Mewtwo",
        "Mew",
        "Chikorita",
        "Bayleef",
        "Meganium",
        "Cyndaquil",
        "Quilava",
        "Typhlosion",
        "Totodile",
        "Croconaw",
        "Feraligatr",
        "Sentret",
        "Furret",
        "Hoothoot",
        "Noctowl",
        "Ledyba",
        "Ledian",
        "Spinarak",
        "Ariados",
        "Crobat",
        "Chinchou",
        "Lanturn",
        "Pichu",
        "Cleffa",
        "Igglybuff",
        "Togepi",
        "Togetic",
        "Natu",
        "Xatu",
        "Mareep",
        "Flaaffy",
        "Ampharos",
        "Bellossom",
        "Marill",
        "Azumarill",
        "Sudowoodo",
        "Politoed",
        "Hoppip",
        "Skiploom",
        "Jumpluff",
        "Aipom",
        "Sunkern",
        "Sunflora",
        "Yanma",
        "Wooper",
        "Quagsire",
        "Espeon",
        "Umbreon",
        "Murkrow",
        "Slowking",
        "Misdreavus",
        "Unown",
        "Wobbuffet",
        "Girafarig",
        "Pineco",
        "Forretress",
        "Dunsparce",
        "Gligar",
        "Steelix",
        "Snubbull",
        "Granbull",
        "Qwilfish",
        "Scizor",
        "Shuckle",
        "Heracross",
        "Sneasel",
        "Teddiursa",
        "Ursaring",
        "Slugma",
        "Magcargo",
        "Swinub",
        "Piloswine",
        "Corsola",
        "Remoraid",
        "Octillery",
        "Delibird",
        "Mantine",
        "Skarmory",
        "Houndour",
        "Houndoom",
        "Kingdra",
        "Phanpy",
        "Donphan",
        "Porygon2",
        "Stantler",
        "Smeargle",
        "Tyrogue",
        "Hitmontop",
        "Smoochum",
        "Elekid",
        "Magby",
        "Miltank",
        "Blissey",
        "Raikou",
        "Entei",
        "Suicune",
        "Larvitar",
        "Pupitar",
        "Tyranitar",
        "Lugia",
        "Ho-Oh",
        "Celebi",
        "Treecko",
        "Grovyle",
        "Sceptile",
        "Torchic",
        "Combusken",
        "Blaziken",
        "Mudkip",
        "Marshtomp",
        "Swampert",
        "Poochyena",
        "Mightyena",
        "Zigzagoon",
        "Linoone",
        "Wurmple",
        "Silcoon",
        "Beautifly",
        "Cascoon",
        "Dustox",
        "Lotad",
        "Lombre",
        "Ludicolo",
        "Seedot",
        "Nuzleaf",
        "Shiftry",
        "Taillow",
        "Swellow",
        "Wingull",
        "Pelipper",
        "Ralts",
        "Kirlia",
        "Gardevoir",
        "Surskit",
        "Masquerain",
        "Shroomish",
        "Breloom",
        "Slakoth",
        "Vigoroth",
        "Slaking",
        "Nincada",
        "Ninjask",
        "Shedinja",
        "Whismur",
        "Loudred",
        "Exploud",
        "Makuhita",
        "Hariyama",
        "Azurill",
        "Nosepass",
        "Skitty",
        "Delcatty",
        "Sableye",
        "Mawile",
        "Aron",
        "Lairon",
        "Aggron",
        "Meditite",
        "Medicham",
        "Electrike",
        "Manectric",
        "Plusle",
        "Minun",
        "Volbeat",
        "Illumise",
        "Roselia",
        "Gulpin",
        "Swalot",
        "Carvanha",
        "Sharpedo",
        "Wailmer",
        "Wailord",
        "Numel",
        "Camerupt",
        "Torkoal",
        "Spoink",
        "Grumpig",
        "Spinda",
        "Trapinch",
        "Vibrava",
        "Flygon",
        "Cacnea",
        "Cacturne",
        "Swablu",
        "Altaria",
        "Zangoose",
        "Seviper",
        "Lunatone",
        "Solrock",
        "Barboach",
        "Whiscash",
        "Corphish",
        "Crawdaunt",
        "Baltoy",
        "Claydol",
        "Lileep",
        "Cradily",
        "Anorith",
        "Armaldo",
        "Feebas",
        "Milotic",
        "Castform",
        "Kecleon",
        "Shuppet",
        "Banette",
        "Duskull",
        "Dusclops",
        "Tropius",
        "Chimecho",
        "Absol",
        "Wynaut",
        "Snorunt",
        "Glalie",
        "Spheal",
        "Sealeo",
        "Walrein",
        "Clamperl",
        "Huntail",
        "Gorebyss",
        "Relicanth",
        "Luvdisc",
        "Bagon",
        "Shelgon",
        "Salamence",
        "Beldum",
        "Metang",
        "Metagross",
        "Regirock",
        "Regice",
        "Registeel",
        "Latias",
        "Latios",
        "Kyogre",
        "Groudon",
        "Rayquaza",
        "Jirachi",
        "Deoxys",
        "Turtwig",
        "Grotle",
        "Torterra",
        "Chimchar",
        "Monferno",
        "Infernape",
        "Piplup",
        "Prinplup",
        "Empoleon",
        "Starly",
        "Staravia",
        "Staraptor",
        "Bidoof",
        "Bibarel",
        "Kricketot",
        "Kricketune",
        "Shinx",
        "Luxio",
        "Luxray",
        "Budew",
        "Roserade",
        "Cranidos",
        "Rampardos",
        "Shieldon",
        "Bastiodon",
        "Burmy",
        "Wormadam",
        "Mothim",
        "Combee",
        "Vespiquen",
        "Pachirisu",
        "Buizel",
        "Floatzel",
        "Cherubi",
        "Cherrim",
        "Shellos",
        "Gastrodon",
        "Ambipom",
        "Drifloon",
        "Drifblim",
        "Buneary",
        "Lopunny",
        "Mismagius",
        "Honchkrow",
        "Glameow",
        "Purugly",
        "Chingling",
        "Stunky",
        "Skuntank",
        "Bronzor",
        "Bronzong",
        "Bonsly",
        "MimeJr",
        "Happiny",
        "Chatot",
        "Spiritomb",
        "Gible",
        "Gabite",
        "Garchomp",
        "Munchlax",
        "Riolu",
        "Lucario",
        "Hippopotas",
        "Hippowdon",
        "Skorupi",
        "Drapion",
        "Croagunk",
        "Toxicroak",
        "Carnivine",
        "Finneon",
        "Lumineon",
        "Mantyke",
        "Snover",
        "Abomasnow",
        "Weavile",
        "Magnezone",
        "Lickilicky",
        "Rhyperior",
        "Tangrowth",
        "Electivire",
        "Magmortar",
        "Togekiss",
        "Yanmega",
        "Leafeon",
        "Glaceon",
        "Gliscor",
        "Mamoswine",
        "PorygonZ",
        "Gallade",
        "Probopass",
        "Dusknoir",
        "Froslass",
        "Rotom",
        "Uxie",
        "Mesprit",
        "Azelf",
        "Dialga",
        "Palkia",
        "Heatran",
        "Regigigas",
        "Giratina",
        "Cresselia",
        "Phione",
        "Manaphy",
        "Darkrai",
        "Shaymin",
        "Arceus",
        "Victini",
        "Snivy",
        "Servine",
        "Serperior",
        "Tepig",
        "Pignite",
        "Emboar",
        "Oshawott",
        "Dewott",
        "Samurott",
        "Patrat",
        "Watchog",
        "Lillipup",
        "Herdier",
        "Stoutland",
        "Purrloin",
        "Liepard",
        "Pansage",
        "Simisage",
        "Pansear",
        "Simisear",
        "Panpour",
        "Simipour",
        "Munna",
        "Musharna",
        "Pidove",
        "Tranquill",
        "Unfezant",
        "Blitzle",
        "Zebstrika",
        "Roggenrola",
        "Boldore",
        "Gigalith",
        "Woobat",
        "Swoobat",
        "Drilbur",
        "Excadrill",
        "Audino",
        "Timburr",
        "Gurdurr",
        "Conkeldurr",
        "Tympole",
        "Palpitoad",
        "Seismitoad",
        "Throh",
        "Sawk",
        "Sewaddle",
        "Swadloon",
        "Leavanny",
        "Venipede",
        "Whirlipede",
        "Scolipede",
        "Cottonee",
        "Whimsicott",
        "Petilil",
        "Lilligant",
        "Basculin",
        "Sandile",
        "Krokorok",
        "Krookodile",
        "Darumaka",
        "Darmanitan",
        "Maractus",
        "Dwebble",
        "Crustle",
        "Scraggy",
        "Scrafty",
        "Sigilyph",
        "Yamask",
        "Cofagrigus",
        "Tirtouga",
        "Carracosta",
        "Archen",
        "Archeops",
        "Trubbish",
        "Garbodor",
        "Zorua",
        "Zoroark",
        "Minccino",
        "Cinccino",
        "Gothita",
        "Gothorita",
        "Gothitelle",
        "Solosis",
        "Duosion",
        "Reuniclus",
        "Ducklett",
        "Swanna",
        "Vanillite",
        "Vanillish",
        "Vanilluxe",
        "Deerling",
        "Sawsbuck",
        "Emolga",
        "Karrablast",
        "Escavalier",
        "Foongus",
        "Amoonguss",
        "Frillish",
        "Jellicent",
        "Alomomola",
        "Joltik",
        "Galvantula",
        "Ferroseed",
        "Ferrothorn",
        "Klink",
        "Klang",
        "Klinklang",
        "Tynamo",
        "Eelektrik",
        "Eelektross",
        "Elgyem",
        "Beheeyem",
        "Litwick",
        "Lampent",
        "Chandelure",
        "Axew",
        "Fraxure",
        "Haxorus",
        "Cubchoo",
        "Beartic",
        "Cryogonal",
        "Shelmet",
        "Accelgor",
        "Stunfisk",
        "Mienfoo",
        "Mienshao",
        "Druddigon",
        "Golett",
        "Golurk",
        "Pawniard",
        "Bisharp",
        "Bouffalant",
        "Rufflet",
        "Braviary",
        "Vullaby",
        "Mandibuzz",
        "Heatmor",
        "Durant",
        "Deino",
        "Zweilous",
        "Hydreigon",
        "Larvesta",
        "Volcarona",
        "Cobalion",
        "Terrakion",
        "Virizion",
        "Tornadus",
        "Thundurus",
        "Reshiram",
        "Zekrom",
        "Landorus",
        "Kyurem",
        "Keldeo",
        "Meloetta",
        "Genesect",
        "Chespin",
        "Quilladin",
        "Chesnaught",
        "Fennekin",
        "Braixen",
        "Delphox",
        "Froakie",
        "Frogadier",
        "Greninja",
        "Bunnelby",
        "Diggersby",
        "Fletchling",
        "Fletchinder",
        "Talonflame",
        "Scatterbug",
        "Spewpa",
        "Vivillon",
        "Litleo",
        "Pyroar",
        "Flabebe",
        "Floette",
        "Florges",
        "Skiddo",
        "Gogoat",
        "Pancham",
        "Pangoro",
        "Furfrou",
        "Espurr",
        "Meowstic",
        "Honedge",
        "Doublade",
        "Aegislash",
        "Spritzee",
        "Aromatisse",
        "Swirlix",
        "Slurpuff",
        "Inkay",
        "Malamar",
        "Binacle",
        "Barbaracle",
        "Skrelp",
        "Dragalge",
        "Clauncher",
        "Clawitzer",
        "Helioptile",
        "Heliolisk",
        "Tyrunt",
        "Tyrantrum",
        "Amaura",
        "Aurorus",
        "Sylveon",
        "Hawlucha",
        "Dedenne",
        "Carbink",
        "Goomy",
        "Sliggoo",
        "Goodra",
        "Klefki",
        "Phantump",
        "Trevenant",
        "Pumpkaboo",
        "Gourgeist",
        "Bergmite",
        "Avalugg",
        "Noibat",
        "Noivern",
        "Xerneas",
        "Yveltal",
        "Zygarde",
        "Diancie",
        "Hoopa",
        "Volcanion"
    };

    extern int speciesID;

    struct Species {
        vector<string> name;
        vector<int> matchValue;
    };

    void SearchForSpecies(MenuEntry *entry);

    static const vector<string> formList(int dex) {
        vector<string> options;

        switch (dex) {
            case 3:   // Venusaur
            case 9:   // Blastoise
            case 65:  // Alakazam
            case 94:  // Gengar
            case 115: // Kangaskhan
            case 127: // Pinsir
            case 130: // Gyarados
            case 142: // Aerodactyl
            case 181: // Ampharos
            case 208: // Steelix
            case 212: // Scizor
            case 214: // Heracross
            case 229: // Houndoom
            case 248: // Tyranitar
            case 257: // Blaziken
            case 282: // Gardevoir
            case 303: // Mawile
            case 306: // Aggron
            case 308: // Medicham
            case 310: // Manectric
            case 354: // Banette
            case 359: // Absol
            case 380: // Latias
            case 381: // Latios
            case 445: // Garchomp
            case 448: // Lucario
            case 460: // Abomasnow
                options = {"Normal", "Mega"};
                break;

            case 6:   // Charizard
            case 150: // Mewtwo
                options = {"Normal", "Mega X", "Mega Y"};
                break;

            case 15:  // Beedrill
            case 18:  // Pidgeot
            case 80:  // Slowbro
            case 254: // Sceptile
            case 260: // Swampert
            case 302: // Sableye
            case 319: // Sharpedo
            case 323: // Camerupt
            case 334: // Altaria
            case 362: // Glalie
            case 373: // Salamence
            case 376: // Metagross
            case 384: // Rayquaza
            case 428: // Lopunny
            case 475: // Gallade
            case 531: // Audino
            case 719: // Diancie
                options = AutoGameSet({"Normal"}, {"Normal", "Mega"});
                break;

            case 201: // Unown
                options = {"A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "!", "?"};
                break;

            case 351: // Castform
                options = {"Normal", "Sunny", "Rainy", "Snowy"};
                break;

            case 382: // Kyogre
            case 383: // Groudon
                options = AutoGameSet({"Normal"}, {"Normal", "Primal"});
                break;

            case 386: // Deoxys
                options = {"Normal", "Attack", "Defense", "Speed"};
                break;

            case 412: // Burmy
            case 413: // Wormadam
            case 414: // Mothim
                options = {"Plant", "Sandy", "Trash"};
                break;

            case 422: // Shellos
            case 423: // Gastrodon
                options = {"East", "West"};
                break;

            case 479: // Rotom
                options = {"Normal", "Heat", "Wash", "Frost", "Fan", "Mow"};
                break;

            case 487: // Giratina
                options = {"Altered", "Origin"};
                break;

            case 492: // Shaymin
                options = {"Land", "Sky"};
                break;

            case 493: // Arceus
                options = {"Normal", "Fighting", "Flying", "Poison", "Ground", "Rock", "Bug", "Ghost", "Steel", "Fire", "Water", "Grass", "Electric", "Psychic", "Ice", "Dragon", "Dark", "Fairy"};
                break;

            case 550: // Basculin
                options = {"Red", "Blue"};
                break;

            case 555: // Darmanitan
                options = {"Standard", "Zen"};
                break;

            case 585: // Deerling
            case 586: // Sawsbuck
                options = {"Spring", "Summer", "Autumn", "Winter"};
                break;

            case 641: // Tornadus
            case 642: // Thundurus
            case 645: // Landorus
                options = {"Incarnate", "Therian"};
                break;

            case 646: // Kyurem
                options = {"Normal", "White", "Black"};
                break;

            case 647: // Keldeo
                options = {"Ordinary", "Resolute"};
                break;

            case 648: // Meloetta
                options = {"Aria", "Pirouette"};
                break;

            case 649: // Genesect
                options = {"Normal", "Douse", "Shock", "Burn", "Chill"};
                break;

            case 664: // Scatterbug
            case 665: // Spewpa
            case 666: // Vivillon
                options = {"Icy Snow", "Polar", "Tundra", "Continental", "Garden", "Elegant", "Meadow", "Modern", "Marine", "Archipelago", "High-Plains", "Sandstorm", "River", "Monsoon", "Savannah", "Sun", "Ocean", "Jungle", "Fancy", "Poké Ball"};
                break;

            case 669: // Flabébé
            case 671: // Florges
                options = {"Red", "Yellow", "Orange", "Blue", "White"};
                break;

            case 670: // Floette
                options = {"Red", "Yellow", "Orange", "Blue", "White", "Eternal"};
                break;

            case 676: // Furfrou
                options = {"Natural", "Heart", "Star", "Diamond", "Deputante", "Matron", "Dandy", "La Reine", "Kabuki", "Pharaoh"};
                break;

            case 681: // Aegislash
                options = {"Shield", "Blade"};
                break;

            case 710: // Pumpkaboo
            case 711: // Gourgeist
                options = {"Average", "Small", "Large", "Super"};
                break;

            case 716: // Xerneas
                options = {"Neutral", "Active"};
                break;

            case 720: // Hoopa
                options = AutoGameSet({"Confined"}, {"Confined", "Unbound"});
                break;

            default:  // All Others
                options = {"Normal"};
                break;
        }

        return options;
    }

    static const char *abilityList[191] = {
        "Stench",
        "Drizzle",
        "Speed Boost",
        "Battle Armor",
        "Sturdy",
        "Damp",
        "Limber",
        "Sand Veil",
        "Static",
        "Volt Absorb",
        "Water Absorb",
        "Oblivious",
        "Cloud Nine",
        "Compound Eyes",
        "Insomnia",
        "Color Change",
        "Immunity",
        "Flash Fire",
        "Shield Dust",
        "Own Tempo",
        "Suction Cups",
        "Intimidate",
        "Shadow Tag",
        "Rough Skin",
        "Wonder Guard",
        "Levitate",
        "Effect Spore",
        "Synchronize",
        "Clear Body",
        "Natural Cure",
        "Lightning Rod",
        "Serene Grace",
        "Swift Swim",
        "Chlorophyll",
        "Illuminate",
        "Trace",
        "Huge Power",
        "Poison Point",
        "Inner Focus",
        "Magma Armor",
        "Water Veil",
        "Magnet Pull",
        "Soundproof",
        "Rain Dish",
        "Sand Stream",
        "Pressure",
        "Thick Fat",
        "Early Bird",
        "Flame Body",
        "Run Away",
        "Keen Eye",
        "Hyper Cutter",
        "Pickup",
        "Truant",
        "Hustle",
        "Cute Charm",
        "Plus",
        "Minus",
        "Forecast",
        "Sticky Hold",
        "Shed Skin",
        "Guts",
        "Marvel Scale",
        "Liquid Ooze",
        "Overgrow",
        "Blaze",
        "Torrent",
        "Swarm",
        "Rock Head",
        "Drought",
        "Arena Trap",
        "Vital Spirit",
        "White Smoke",
        "Pure Power",
        "Shell Armor",
        "Air Lock",
        "Tangled Feet",
        "Motor Drive",
        "Rivalry",
        "Steadfast",
        "Snow Cloak",
        "Gluttony",
        "Anger Point",
        "Unburden",
        "Heatproof",
        "Simple",
        "Dry Skin",
        "Download",
        "Iron Fist",
        "Poison Heal",
        "Adaptability",
        "Skill Link",
        "Hydration",
        "Solar Power",
        "Quick Feet",
        "Normalize",
        "Sniper",
        "Magic Guard",
        "No Guard",
        "Stall",
        "Technician",
        "Leaf Guard",
        "Klutz",
        "Mold Breaker",
        "Super Luck",
        "Aftermath",
        "Anticipation",
        "Forewarn",
        "Unaware",
        "Tinted Lens",
        "Filter",
        "Slow Start",
        "Scrappy",
        "Storm Drain",
        "Ice Body",
        "Solid Rock",
        "Snow Warning",
        "Honey Gather",
        "Frisk",
        "Reckless",
        "Multitype",
        "Flower Gift",
        "Bad Dreams",
        "Pickpocket",
        "Sheer Force",
        "Contrary",
        "Unnerve",
        "Defiant",
        "Defeatist",
        "Cursed Body",
        "Healer",
        "Friend Guard",
        "Weak Armor",
        "Heavy Metal",
        "Light Metal",
        "Multiscale",
        "Toxic Boost",
        "Flare Boost",
        "Harvest",
        "Telepathy",
        "Moody",
        "Overcoat",
        "Poison Touch",
        "Regenerator",
        "Big Pecks",
        "Sand Rush",
        "Wonder Skin",
        "Analytic",
        "Illusion",
        "Imposter",
        "Infiltrator",
        "Mummy",
        "Moxie",
        "Justified",
        "Rattled",
        "Magic Bounce",
        "Sap Sipper",
        "Prankster",
        "Sand Force",
        "Iron Barbs",
        "Zen Mode",
        "Victory Star",
        "Turboblaze",
        "Teravolt",
        "Aroma Veil",
        "Flower Veil",
        "Cheek Pouch",
        "Protean",
        "Fur Coat",
        "Magician",
        "Bulletproof",
        "Competitive",
        "Strong Jaw",
        "Refrigerate",
        "Sweet Veil",
        "Stance Change",
        "Gale Wings",
        "Mega Launcher",
        "Grass Pelt",
        "Symbiosis",
        "Tough Claws",
        "Pixilate",
        "Gooey",
        "Aerilate",
        "Parental Bond",
        "Dark Aura",
        "Fairy Aura",
        "Aura Break",
        "Primordial Sea",
        "Desolate Land",
        "Delta Stream"
    };

    extern int abilityName;

    struct Ability {
        vector<string> name;
        vector<int> matchValue;
    };

    void SearchForAbility(MenuEntry *entry);

    static const char *heldItemList[775] = {
        "Master Ball",
        "Ultra Ball",
        "Great Ball",
        "Poké Ball",
        "Safari Ball",
        "Net Ball",
        "Dive Ball",
        "Nest Ball",
        "Repeat Ball",
        "Timer Ball",
        "Luxury Ball",
        "Premier Ball",
        "Dusk Ball",
        "Heal Ball",
        "Quick Ball",
        "Cherish Ball",
        "Potion",
        "Antidote",
        "Burn Heal",
        "Ice Heal",
        "Awakening",
        "Paralyze Heal",
        "Full Restore",
        "Max Potion",
        "Hyper Potion",
        "Super Potion",
        "Full Heal",
        "Revive",
        "Max Revive",
        "Fresh Water",
        "Soda Pop",
        "Lemonade",
        "Moomoo Milk",
        "Energy Powder",
        "Energy Root",
        "Heal Powder",
        "Revival Herb",
        "Ether",
        "Max Ether",
        "Elixir",
        "Max Elixir",
        "Lava Cookie",
        "Berry Juice",
        "Sacred Ash",
        "HP Up",
        "Protein",
        "Iron",
        "Carbos",
        "Calcium",
        "Rare Candy",
        "PP Up",
        "Zinc",
        "PP Max",
        "Old Gateau",
        "Guard Spec.",
        "Dire Hit",
        "X Attack",
        "X Defense",
        "X Speed",
        "X Accuracy",
        "X Sp. Atk",
        "X Sp. Def",
        "Poké Doll",
        "Fluffy Tail",
        "Blue Flute",
        "Yellow Flute",
        "Red Flute",
        "Black Flute",
        "White Flute",
        "Shoal Salt",
        "Shoal Shell",
        "Red Shard",
        "Blue Shard",
        "Yellow Shard",
        "Green Shard",
        "Super Repel",
        "Max Repel",
        "Escape Rope",
        "Repel",
        "Sun Stone",
        "Moon Stone",
        "Fire Stone",
        "Thunder Stone",
        "Water Stone",
        "Leaf Stone",
        "Tiny Mushroom",
        "Big Mushroom",
        "Pearl",
        "Big Pearl",
        "Stardust",
        "Star Piece",
        "Nugget",
        "Heart Scale",
        "Honey",
        "Growth Mulch",
        "Damp Mulch",
        "Stable Mulch",
        "Gooey Mulch",
        "Root Fossil",
        "Claw Fossil",
        "Helix Fossil",
        "Dome Fossil",
        "Old Amber",
        "Armor Fossil",
        "Skull Fossil",
        "Rare Bone",
        "Shiny Stone",
        "Dusk Stone",
        "Dawn Stone",
        "Oval Stone",
        "Odd Keystone",
        "Griseous Orb",
        "Tea",
        "???",
        "Autograph",
        "Douse Drive",
        "Shock Drive",
        "Burn Drive",
        "Chill Drive",
        "???",
        "Pokemon Box Link",
        "Medicine Pocket",
        "TM Case",
        "Candy Jar",
        "Power-Up Pocket",
        "Clothing Trunk",
        "Catching Pocket",
        "Battle Pocket",
        "???",
        "???",
        "???",
        "???",
        "???",
        "Sweet Heart",
        "Adamant Orb",
        "Lustrous Orb",
        "Greet Mail",
        "Favored Mail",
        "RSVP Mail",
        "Thanks Mail",
        "Inquiry Mail",
        "Like Mail",
        "Reply Mail",
        "Bridge Mail S",
        "Bridge Mail D",
        "Bridge Mail T",
        "Bridge Mail V",
        "Bridge Mail M",
        "Cheri Berry",
        "Chesto Berry",
        "Pecha Berry",
        "Rawst Berry",
        "Aspear Berry",
        "Leppa Berry",
        "Oran Berry",
        "Persim Berry",
        "Lum Berry",
        "Sitrus Berry",
        "Figy Berry",
        "Wiki Berry",
        "Mago Berry",
        "Aguav Berry",
        "Iapapa Berry",
        "Razz Berry",
        "Bluk Berry",
        "Nanab Berry",
        "Wepear Berry",
        "Pinap Berry",
        "Pomeg Berry",
        "Kelpsy Berry",
        "Qualot Berry",
        "Hondew Berry",
        "Grepa Berry",
        "Tamato Berry",
        "Cornn Berry",
        "Magost Berry",
        "Rabuta Berry",
        "Nomel Berry",
        "Spelon Berry",
        "Pamtre Berry",
        "Watmel Berry",
        "Durin Berry",
        "Belue Berry",
        "Occa Berry",
        "Passho Berry",
        "Wacan Berry",
        "Rindo Berry",
        "Yache Berry",
        "Chople Berry",
        "Kebia Berry",
        "Shuca Berry",
        "Coba Berry",
        "Payapa Berry",
        "Tanga Berry",
        "Charti Berry",
        "Kasib Berry",
        "Haban Berry",
        "Colbur Berry",
        "Babiri Berry",
        "Chilan Berry",
        "Liechi Berry",
        "Ganlon Berry",
        "Salac Berry",
        "Petaya Berry",
        "Apicot Berry",
        "Lansat Berry",
        "Starf Berry",
        "Enigma Berry",
        "Micle Berry",
        "Custap Berry",
        "Jaboca Berry",
        "Rowap Berry",
        "Bright Powder",
        "White Herb",
        "Macho Brace",
        "Exp. Share",
        "Quick Claw",
        "Soothe Bell",
        "Mental Herb",
        "Choice Band",
        "King’s Rock",
        "Silver Powder",
        "Amulet Coin",
        "Cleanse Tag",
        "Soul Dew",
        "Deep Sea Tooth",
        "Deep Sea Scale",
        "Smoke Ball",
        "Everstone",
        "Focus Band",
        "Lucky Egg",
        "Scope Lens",
        "Metal Coat",
        "Leftovers",
        "Dragon Scale",
        "Light Ball",
        "Soft Sand",
        "Hard Stone",
        "Miracle Seed",
        "Black Glasses",
        "Black Belt",
        "Magnet",
        "Mystic Water",
        "Sharp Beak",
        "Poison Barb",
        "Never-Melt Ice",
        "Spell Tag",
        "Twisted Spoon",
        "Charcoal",
        "Dragon Fang",
        "Silk Scarf",
        "Upgrade",
        "Shell Bell",
        "Sea Incense",
        "Lax Incense",
        "Lucky Punch",
        "Metal Powder",
        "Thick Club",
        "Leek",
        "Red Scarf",
        "Blue Scarf",
        "Pink Scarf",
        "Green Scarf",
        "Yellow Scarf",
        "Wide Lens",
        "Muscle Band",
        "Wise Glasses",
        "Expert Belt",
        "Light Clay",
        "Life Orb",
        "Power Herb",
        "Toxic Orb",
        "Flame Orb",
        "Quick Powder",
        "Focus Sash",
        "Zoom Lens",
        "Metronome",
        "Iron Ball",
        "Lagging Tail",
        "Destiny Knot",
        "Black Sludge",
        "Icy Rock",
        "Smooth Rock",
        "Heat Rock",
        "Damp Rock",
        "Grip Claw",
        "Choice Scarf",
        "Sticky Barb",
        "Power Bracer",
        "Power Belt",
        "Power Lens",
        "Power Band",
        "Power Anklet",
        "Power Weight",
        "Shed Shell",
        "Big Root",
        "Choice Specs",
        "Flame Plate",
        "Splash Plate",
        "Zap Plate",
        "Meadow Plate",
        "Icicle Plate",
        "Fist Plate",
        "Toxic Plate",
        "Earth Plate",
        "Sky Plate",
        "Mind Plate",
        "Insect Plate",
        "Stone Plate",
        "Spooky Plate",
        "Draco Plate",
        "Dread Plate",
        "Iron Plate",
        "Odd Incense",
        "Rock Incense",
        "Full Incense",
        "Wave Incense",
        "Rose Incense",
        "Luck Incense",
        "Pure Incense",
        "Protector",
        "Electirizer",
        "Magmarizer",
        "Dubious Disc",
        "Reaper Cloth",
        "Razor Claw",
        "Razor Fang",
        "TM01",
        "TM02",
        "TM03",
        "TM04",
        "TM05",
        "TM06",
        "TM07",
        "TM08",
        "TM09",
        "TM10",
        "TM11",
        "TM12",
        "TM13",
        "TM14",
        "TM15",
        "TM16",
        "TM17",
        "TM18",
        "TM19",
        "TM20",
        "TM21",
        "TM22",
        "TM23",
        "TM24",
        "TM25",
        "TM26",
        "TM27",
        "TM28",
        "TM29",
        "TM30",
        "TM31",
        "TM32",
        "TM33",
        "TM34",
        "TM35",
        "TM36",
        "TM37",
        "TM38",
        "TM39",
        "TM40",
        "TM41",
        "TM42",
        "TM43",
        "TM44",
        "TM45",
        "TM46",
        "TM47",
        "TM48",
        "TM49",
        "TM50",
        "TM51",
        "TM52",
        "TM53",
        "TM54",
        "TM55",
        "TM56",
        "TM57",
        "TM58",
        "TM59",
        "TM60",
        "TM61",
        "TM62",
        "TM63",
        "TM64",
        "TM65",
        "TM66",
        "TM67",
        "TM68",
        "TM69",
        "TM70",
        "TM71",
        "TM72",
        "TM73",
        "TM74",
        "TM75",
        "TM76",
        "TM77",
        "TM78",
        "TM79",
        "TM80",
        "TM81",
        "TM82",
        "TM83",
        "TM84",
        "TM85",
        "TM86",
        "TM87",
        "TM88",
        "TM89",
        "TM90",
        "TM91",
        "TM92",
        "HM01",
        "HM02",
        "HM03",
        "HM04",
        "HM05",
        "HM06",
        "???",
        "???",
        "Explorer Kit",
        "Loot Sack",
        "Rule Book",
        "Poké Radar",
        "Point Card",
        "Journal",
        "Seal Case",
        "Fashion Case",
        "Seal Bag",
        "Pal Pad",
        "Works Key",
        "Old Charm",
        "Galactic Key",
        "Red Chain",
        "Town Map",
        "Vs. Seeker",
        "Coin Case",
        "Old Rod",
        "Good Rod",
        "Super Rod",
        "Sprayduck",
        "Poffin Case",
        "Bike",
        "Suite Key",
        "Oak’s Letter",
        "Lunar Wing",
        "Member Card",
        "Azure Flute",
        "S.S. Ticket",
        "Contest Pass",
        "Magma Stone",
        "Parcel",
        "Coupon 1",
        "Coupon 2",
        "Coupon 3",
        "Storage Key",
        "Secret Potion",
        "Vs. Recorder",
        "Gracidea",
        "Secret Key",
        "Apricorn Box",
        "Unown Report",
        "Berry Pots",
        "Dowsing Machine",
        "Blue Card",
        "Slowpoke Tail",
        "Clear Bell",
        "Card Key",
        "Basement Key",
        "Squirt Bottle",
        "Red Scale",
        "Lost Item",
        "Pass",
        "Machine Part",
        "Silver Wing",
        "Rainbow Wing",
        "Mystery Egg",
        "Red Apricorn",
        "Blue Apricorn",
        "Yellow Apricorn",
        "Green Apricorn",
        "Pink Apricorn",
        "White Apricorn",
        "Black Apricorn",
        "Fast Ball",
        "Level Ball",
        "Lure Ball",
        "Heavy Ball",
        "Love Ball",
        "Friend Ball",
        "Moon Ball",
        "Sport Ball",
        "Park Ball",
        "Photo Album",
        "GB Sounds",
        "Tidal Bell",
        "Rage Candy Bar",
        "Data Card 01",
        "Data Card 02",
        "Data Card 03",
        "Data Card 04",
        "Data Card 05",
        "Data Card 06",
        "Data Card 07",
        "Data Card 08",
        "Data Card 09",
        "Data Card 10",
        "Data Card 11",
        "Data Card 12",
        "Data Card 13",
        "Data Card 14",
        "Data Card 15",
        "Data Card 16",
        "Data Card 17",
        "Data Card 18",
        "Data Card 19",
        "Data Card 20",
        "Data Card 21",
        "Data Card 22",
        "Data Card 23",
        "Data Card 24",
        "Data Card 25",
        "Data Card 26",
        "Data Card 27",
        "Jade Orb",
        "Lock Capsule",
        "Red Orb",
        "Blue Orb",
        "Enigma Stone",
        "Prism Scale",
        "Eviolite",
        "Float Stone",
        "Rocky Helmet",
        "Air Balloon",
        "Red Card",
        "Ring Target",
        "Binding Band",
        "Absorb Bulb",
        "Cell Battery",
        "Eject Button",
        "Fire Gem",
        "Water Gem",
        "Electric Gem",
        "Grass Gem",
        "Ice Gem",
        "Fighting Gem",
        "Poison Gem",
        "Ground Gem",
        "Flying Gem",
        "Psychic Gem",
        "Bug Gem",
        "Rock Gem",
        "Ghost Gem",
        "Dragon Gem",
        "Dark Gem",
        "Steel Gem",
        "Normal Gem",
        "Health Feather",
        "Muscle Feather",
        "Resist Feather",
        "Genius Feather",
        "Clever Feather",
        "Swift Feather",
        "Pretty Feather",
        "Cover Fossil",
        "Plume Fossil",
        "Liberty Pass",
        "Pass Orb",
        "Dream Ball",
        "Poké Toy",
        "Prop Case",
        "Dragon Skull",
        "Balm Mushroom",
        "Big Nugget",
        "Pearl String",
        "Comet Shard",
        "Relic Copper",
        "Relic Silver",
        "Relic Gold",
        "Relic Vase",
        "Relic Band",
        "Relic Statue",
        "Relic Crown",
        "Casteliacone",
        "Dire Hit 2",
        "X Speed 2",
        "X Sp. Atk 2",
        "X Sp. Def 2",
        "X Defense 2",
        "X Attack 2",
        "X Accuracy 2",
        "X Speed 3",
        "X Sp. Atk 3",
        "X Sp. Def 3",
        "X Defense 3",
        "X Attack 3",
        "X Accuracy 3",
        "X Speed 6",
        "X Sp. Atk 6",
        "X Sp. Def 6",
        "X Defense 6",
        "X Attack 6",
        "X Accuracy 6",
        "Ability Urge",
        "Item Drop",
        "Item Urge",
        "Reset Urge",
        "Dire Hit 3",
        "Light Stone",
        "Dark Stone",
        "TM93",
        "TM94",
        "TM95",
        "Xtransceiver",
        "???",
        "Gram 1",
        "Gram 2",
        "Gram 3",
        "Xtransceiver",
        "Medal Box",
        "DNA Splicers",
        "DNA Splicers",
        "Permit",
        "Oval Charm",
        "Shiny Charm",
        "Plasma Card",
        "Grubby Hanky",
        "Colress Machine",
        "Dropped Item",
        "Dropped Item",
        "Reveal Glass",
        "Weakness Policy",
        "Assault Vest",
        "Holo Caster",
        "Prof’s Letter",
        "Roller Skates",
        "Pixie Plate",
        "Ability Capsule",
        "Whipped Dream",
        "Sachet",
        "Luminous Moss",
        "Snowball",
        "Safety Goggles",
        "Poké Flute",
        "Rich Mulch",
        "Surprise Mulch",
        "Boost Mulch",
        "Amaze Mulch",
        "Gengarite",
        "Gardevoirite",
        "Ampharosite",
        "Venusaurite",
        "Charizardite X",
        "Blastoisinite",
        "Mewtwonite X",
        "Mewtwonite Y",
        "Blazikenite",
        "Medichamite",
        "Houndoominite",
        "Aggronite",
        "Banettite",
        "Tyranitarite",
        "Scizorite",
        "Pinsirite",
        "Aerodactylite",
        "Lucarionite",
        "Abomasite",
        "Kangaskhanite",
        "Gyaradosite",
        "Absolite",
        "Charizardite Y",
        "Alakazite",
        "Heracronite",
        "Mawilite",
        "Manectite",
        "Garchompite",
        "Latiasite",
        "Latiosite",
        "Roseli Berry",
        "Kee Berry",
        "Maranga Berry",
        "Sprinklotad",
        "TM96",
        "TM97",
        "TM98",
        "TM99",
        "TM100",
        "Power Plant Pass",
        "Mega Ring",
        "Intriguing Stone",
        "Common Stone",
        "Discount Coupon",
        "Elevator Key",
        "TMV Pass",
        "Honor of Kalos",
        "Adventure Guide",
        "Strange Souvenir",
        "Lens Case",
        "Makeup Bag",
        "Travel Trunk",
        "Lumiose Galette",
        "Shalour Sable",
        "Jaw Fossil",
        "Sail Fossil",
        "Looker Ticket",
        "Bike",
        "Holo Caster",
        "Fairy Gem",
        "Mega Charm",
        "Mega Glove",
        "Mach Bike",
        "Acro Bike",
        "Wailmer Pail",
        "Devon Parts",
        "Soot Sack",
        "Basement Key",
        "Pokéblock Kit",
        "Letter",
        "Eon Ticket",
        "Scanner",
        "Go-Goggles",
        "Meteorite",
        "Key to Room 1",
        "Key to Room 2",
        "Key to Room 4",
        "Key to Room 6",
        "Storage Key",
        "Devon Scope",
        "S.S. Ticket",
        "HM07",
        "Devon Scuba Gear",
        "Contest Costume",
        "Contest Costume",
        "Magma Suit",
        "Aqua Suit",
        "Pair of Tickets",
        "Mega Bracelet",
        "Mega Pendant",
        "Mega Glasses",
        "Mega Anchor",
        "Mega Stickpin",
        "Mega Tiara",
        "Mega Anklet",
        "Meteorite",
        "Swampertite",
        "Sceptilite",
        "Sablenite",
        "Altarianite",
        "Galladite",
        "Audinite",
        "Metagrossite",
        "Sharpedonite",
        "Slowbronite",
        "Steelixite",
        "Pidgeotite",
        "Glalitite",
        "Diancite",
        "Prison Bottle",
        "Mega Cuff",
        "Cameruptite",
        "Lopunnite",
        "Salamencite",
        "Beedrillite",
        "Meteorite",
        "Meteorite",
        "Key Stone",
        "Meteorite Shard",
        "Eon Flute"
    };

    extern int heldItemName;

    struct HeldItem {
        vector<string> name;
        vector<int> matchValue;
    };

    void SearchForItem(MenuEntry *entry);

    static const char *movesList[621] = {
        "Pound",
        "Karate Chop",
        "Double Slap",
        "Comet Punch",
        "Mega Punch",
        "Pay Day",
        "Fire Punch",
        "Ice Punch",
        "Thunder Punch",
        "Scratch",
        "Vise Grip",
        "Guillotine",
        "Razor Wind",
        "Swords Dance",
        "Cut",
        "Gust",
        "Wing Attack",
        "Whirlwind",
        "Fly",
        "Bind",
        "Slam",
        "Vine Whip",
        "Stomp",
        "Double Kick",
        "Mega Kick",
        "Jump Kick",
        "Rolling Kick",
        "Sand Attack",
        "Headbutt",
        "Horn Attack",
        "Fury Attack",
        "Horn Drill",
        "Tackle",
        "Body Slam",
        "Wrap",
        "Take Down",
        "Thrash",
        "Double-Edge",
        "Tail Whip",
        "Poison Sting",
        "Twineedle",
        "Pin Missile",
        "Leer",
        "Bite",
        "Growl",
        "Roar",
        "Sing",
        "Supersonic",
        "Sonic Boom",
        "Disable",
        "Acid",
        "Ember",
        "Flamethrower",
        "Mist",
        "Water Gun",
        "Hydro Pump",
        "Surf",
        "Ice Beam",
        "Blizzard",
        "Psybeam",
        "Bubble Beam",
        "Aurora Beam",
        "Hyper Beam",
        "Peck",
        "Drill Peck",
        "Submission",
        "Low Kick",
        "Counter",
        "Seismic Toss",
        "Strength",
        "Absorb",
        "Mega Drain",
        "Leech Seed",
        "Growth",
        "Razor Leaf",
        "Solar Beam",
        "Poison Powder",
        "Stun Spore",
        "Sleep Powder",
        "Petal Dance",
        "String Shot",
        "Dragon Rage",
        "Fire Spin",
        "Thunder Shock",
        "Thunderbolt",
        "Thunder Wave",
        "Thunder",
        "Rock Throw",
        "Earthquake",
        "Fissure",
        "Dig",
        "Toxic",
        "Confusion",
        "Psychic",
        "Hypnosis",
        "Meditate",
        "Agility",
        "Quick Attack",
        "Rage",
        "Teleport",
        "Night Shade",
        "Mimic",
        "Screech",
        "Double Team",
        "Recover",
        "Harden",
        "Minimize",
        "Smokescreen",
        "Confuse Ray",
        "Withdraw",
        "Defense Curl",
        "Barrier",
        "Light Screen",
        "Haze",
        "Reflect",
        "Focus Energy",
        "Bide",
        "Metronome",
        "Mirror Move",
        "Self-Destruct",
        "Egg Bomb",
        "Lick",
        "Smog",
        "Sludge",
        "Bone Club",
        "Fire Blast",
        "Waterfall",
        "Clamp",
        "Swift",
        "Skull Bash",
        "Spike Cannon",
        "Constrict",
        "Amnesia",
        "Kinesis",
        "Soft-Boiled",
        "High Jump Kick",
        "Glare",
        "Dream Eater",
        "Poison Gas",
        "Barrage",
        "Leech Life",
        "Lovely Kiss",
        "Sky Attack",
        "Transform",
        "Bubble",
        "Dizzy Punch",
        "Spore",
        "Flash",
        "Psywave",
        "Splash",
        "Acid Armor",
        "Crabhammer",
        "Explosion",
        "Fury Swipes",
        "Bonemerang",
        "Rest",
        "Rock Slide",
        "Hyper Fang",
        "Sharpen",
        "Conversion",
        "Tri Attack",
        "Super Fang",
        "Slash",
        "Substitute",
        "Struggle",
        "Sketch",
        "Triple Kick",
        "Thief",
        "Spider Web",
        "Mind Reader",
        "Nightmare",
        "Flame Wheel",
        "Snore",
        "Curse",
        "Flail",
        "Conversion 2",
        "Aeroblast",
        "Cotton Spore",
        "Reversal",
        "Spite",
        "Powder Snow",
        "Protect",
        "Mach Punch",
        "Scary Face",
        "Feint Attack",
        "Sweet Kiss",
        "Belly Drum",
        "Sludge Bomb",
        "Mud-Slap",
        "Octazooka",
        "Spikes",
        "Zap Cannon",
        "Foresight",
        "Destiny Bond",
        "Perish Song",
        "Icy Wind",
        "Detect",
        "Bone Rush",
        "Lock-On",
        "Outrage",
        "Sandstorm",
        "Giga Drain",
        "Endure",
        "Charm",
        "Rollout",
        "False Swipe",
        "Swagger",
        "Milk Drink",
        "Spark",
        "Fury Cutter",
        "Steel Wing",
        "Mean Look",
        "Attract",
        "Sleep Talk",
        "Heal Bell",
        "Return",
        "Present",
        "Frustration",
        "Safeguard",
        "Pain Split",
        "Sacred Fire",
        "Magnitude",
        "Dynamic Punch",
        "Megahorn",
        "Dragon Breath",
        "Baton Pass",
        "Encore",
        "Pursuit",
        "Rapid Spin",
        "Sweet Scent",
        "Iron Tail",
        "Metal Claw",
        "Vital Throw",
        "Morning Sun",
        "Synthesis",
        "Moonlight",
        "Hidden Power",
        "Cross Chop",
        "Twister",
        "Rain Dance",
        "Sunny Day",
        "Crunch",
        "Mirror Coat",
        "Psych Up",
        "Extreme Speed",
        "Ancient Power",
        "Shadow Ball",
        "Future Sight",
        "Rock Smash",
        "Whirlpool",
        "Beat Up",
        "Fake Out",
        "Uproar",
        "Stockpile",
        "Spit Up",
        "Swallow",
        "Heat Wave",
        "Hail",
        "Torment",
        "Flatter",
        "Will-O-Wisp",
        "Memento",
        "Facade",
        "Focus Punch",
        "Smelling Salts",
        "Follow Me",
        "Nature Power",
        "Charge",
        "Taunt",
        "Helping Hand",
        "Trick",
        "Role Play",
        "Wish",
        "Assist",
        "Ingrain",
        "Superpower",
        "Magic Coat",
        "Recycle",
        "Revenge",
        "Brick Break",
        "Yawn",
        "Knock Off",
        "Endeavor",
        "Eruption",
        "Skill Swap",
        "Imprison",
        "Refresh",
        "Grudge",
        "Snatch",
        "Secret Power",
        "Dive",
        "Arm Thrust",
        "Camouflage",
        "Tail Glow",
        "Luster Purge",
        "Mist Ball",
        "Feather Dance",
        "Teeter Dance",
        "Blaze Kick",
        "Mud Sport",
        "Ice Ball",
        "Needle Arm",
        "Slack Off",
        "Hyper Voice",
        "Poison Fang",
        "Crush Claw",
        "Blast Burn",
        "Hydro Cannon",
        "Meteor Mash",
        "Astonish",
        "Weather Ball",
        "Aromatherapy",
        "Fake Tears",
        "Air Cutter",
        "Overheat",
        "Odor Sleuth",
        "Rock Tomb",
        "Silver Wind",
        "Metal Sound",
        "Grass Whistle",
        "Tickle",
        "Cosmic Power",
        "Water Spout",
        "Signal Beam",
        "Shadow Punch",
        "Extrasensory",
        "Sky Uppercut",
        "Sand Tomb",
        "Sheer Cold",
        "Muddy Water",
        "Bullet Seed",
        "Aerial Ace",
        "Icicle Spear",
        "Iron Defense",
        "Block",
        "Howl",
        "Dragon Claw",
        "Frenzy Plant",
        "Bulk Up",
        "Bounce",
        "Mud Shot",
        "Poison Tail",
        "Covet",
        "Volt Tackle",
        "Magical Leaf",
        "Water Sport",
        "Calm Mind",
        "Leaf Blade",
        "Dragon Dance",
        "Rock Blast",
        "Shock Wave",
        "Water Pulse",
        "Doom Desire",
        "Psycho Boost",
        "Roost",
        "Gravity",
        "Miracle Eye",
        "Wake-Up Slap",
        "Hammer Arm",
        "Gyro Ball",
        "Healing Wish",
        "Brine",
        "Natural Gift",
        "Feint",
        "Pluck",
        "Tailwind",
        "Acupressure",
        "Metal Burst",
        "U-turn",
        "Close Combat",
        "Payback",
        "Assurance",
        "Embargo",
        "Fling",
        "Psycho Shift",
        "Trump Card",
        "Heal Block",
        "Wring Out",
        "Power Trick",
        "Gastro Acid",
        "Lucky Chant",
        "Me First",
        "Copycat",
        "Power Swap",
        "Guard Swap",
        "Punishment",
        "Last Resort",
        "Worry Seed",
        "Sucker Punch",
        "Toxic Spikes",
        "Heart Swap",
        "Aqua Ring",
        "Magnet Rise",
        "Flare Blitz",
        "Force Palm",
        "Aura Sphere",
        "Rock Polish",
        "Poison Jab",
        "Dark Pulse",
        "Night Slash",
        "Aqua Tail",
        "Seed Bomb",
        "Air Slash",
        "X-Scissor",
        "Bug Buzz",
        "Dragon Pulse",
        "Dragon Rush",
        "Power Gem",
        "Drain Punch",
        "Vacuum Wave",
        "Focus Blast",
        "Energy Ball",
        "Brave Bird",
        "Earth Power",
        "Switcheroo",
        "Giga Impact",
        "Nasty Plot",
        "Bullet Punch",
        "Avalanche",
        "Ice Shard",
        "Shadow Claw",
        "Thunder Fang",
        "Ice Fang",
        "Fire Fang",
        "Shadow Sneak",
        "Mud Bomb",
        "Psycho Cut",
        "Zen Headbutt",
        "Mirror Shot",
        "Flash Cannon",
        "Rock Climb",
        "Defog",
        "Trick Room",
        "Draco Meteor",
        "Discharge",
        "Lava Plume",
        "Leaf Storm",
        "Power Whip",
        "Rock Wrecker",
        "Cross Poison",
        "Gunk Shot",
        "Iron Head",
        "Magnet Bomb",
        "Stone Edge",
        "Captivate",
        "Stealth Rock",
        "Grass Knot",
        "Chatter",
        "Judgment",
        "Bug Bite",
        "Charge Beam",
        "Wood Hammer",
        "Aqua Jet",
        "Attack Order",
        "Defend Order",
        "Heal Order",
        "Head Smash",
        "Double Hit",
        "Roar of Time",
        "Spacial Rend",
        "Lunar Dance",
        "Crush Grip",
        "Magma Storm",
        "Dark Void",
        "Seed Flare",
        "Ominous Wind",
        "Shadow Force",
        "Hone Claws",
        "Wide Guard",
        "Guard Split",
        "Power Split",
        "Wonder Room",
        "Psyshock",
        "Venoshock",
        "Autotomize",
        "Rage Powder",
        "Telekinesis",
        "Magic Room",
        "Smack Down",
        "Storm Throw",
        "Flame Burst",
        "Sludge Wave",
        "Quiver Dance",
        "Heavy Slam",
        "Synchronoise",
        "Electro Ball",
        "Soak",
        "Flame Charge",
        "Coil",
        "Low Sweep",
        "Acid Spray",
        "Foul Play",
        "Simple Beam",
        "Entrainment",
        "After You",
        "Round",
        "Echoed Voice",
        "Chip Away",
        "Clear Smog",
        "Stored Power",
        "Quick Guard",
        "Ally Switch",
        "Scald",
        "Shell Smash",
        "Heal Pulse",
        "Hex",
        "Sky Drop",
        "Shift Gear",
        "Circle Throw",
        "Incinerate",
        "Quash",
        "Acrobatics",
        "Reflect Type",
        "Retaliate",
        "Final Gambit",
        "Bestow",
        "Inferno",
        "Water Pledge",
        "Fire Pledge",
        "Grass Pledge",
        "Volt Switch",
        "Struggle Bug",
        "Bulldoze",
        "Frost Breath",
        "Dragon Tail",
        "Work Up",
        "Electroweb",
        "Wild Charge",
        "Drill Run",
        "Dual Chop",
        "Heart Stamp",
        "Horn Leech",
        "Sacred Sword",
        "Razor Shell",
        "Heat Crash",
        "Leaf Tornado",
        "Steamroller",
        "Cotton Guard",
        "Night Daze",
        "Psystrike",
        "Tail Slap",
        "Hurricane",
        "Head Charge",
        "Gear Grind",
        "Searing Shot",
        "Techno Blast",
        "Relic Song",
        "Secret Sword",
        "Glaciate",
        "Bolt Strike",
        "Blue Flare",
        "Fiery Dance",
        "Freeze Shock",
        "Ice Burn",
        "Snarl",
        "Icicle Crash",
        "V-create",
        "Fusion Flare",
        "Fusion Bolt",
        "Flying Press",
        "Mat Block",
        "Belch",
        "Rototiller",
        "Sticky Web",
        "Fell Stinger",
        "Phantom Force",
        "Trick-or-Treat",
        "Noble Roar",
        "Ion Deluge",
        "Parabolic Charge",
        "Forest's Curse",
        "Petal Blizzard",
        "Freeze-Dry",
        "Disarming Voice",
        "Parting Shot",
        "Topsy-Turvy",
        "Draining Kiss",
        "Crafty Shield",
        "Flower Shield",
        "Grassy Terrain",
        "Misty Terrain",
        "Electrify",
        "Play Rough",
        "Fairy Wind",
        "Moonblast",
        "Boomburst",
        "Fairy Lock",
        "King's Shield",
        "Play Nice",
        "Confide",
        "Diamond Storm",
        "Steam Eruption",
        "Hyperspace Hole",
        "Water Shuriken",
        "Mystical Fire",
        "Spiky Shield",
        "Aromatic Mist",
        "Eerie Impulse",
        "Venom Drench",
        "Powder",
        "Geomancy",
        "Magnetic Flux",
        "Happy Hour",
        "Electric Terrain",
        "Dazzling Gleam",
        "Celebrate",
        "Hold Hands",
        "Baby-Doll Eyes",
        "Nuzzle",
        "Hold Back",
        "Infestation",
        "Power-Up Punch",
        "Oblivion Wing",
        "Thousand Arrows",
        "Thousand Waves",
        "Land's Wrath",
        "Light of Ruin",
        "Origin Pulse",
        "Precipice Blades",
        "Dragon Ascent",
        "Hyperspace Fury"
    };

    extern int moveName;

    struct Moves {
        vector<string> name;
        vector<int> matchValue;
    };

    void SearchForMove(MenuEntry *entry);

    static const vector<string> natureList = {
        "Hardy",
        "Lonely",
        "Brave",
        "Adamant",
        "Naughty",
        "Bold",
        "Docile",
        "Relaxed",
        "Impish",
        "Lax",
        "Timid",
        "Hasty",
        "Serious",
        "Jolly",
        "Naive",
        "Modest",
        "Mild",
        "Quiet",
        "Bashful",
        "Rash",
        "Calm",
        "Gentle",
        "Sassy",
        "Careful",
        "Quirky"
    };

    struct Origins {
        const char *name;
        int matchValue;
        int generationFrom;
    };

    static const Origins originList[30] = {
        {"X", 24, 6},
        {"Y", 25, 6},
        {"Omega Ruby", 27, 6},
        {"Alpha Sapphire", 26, 6},
        {"Black", 21, 5},
        {"White", 20, 5},
        {"Black 2", 23, 5},
        {"White 2", 22, 5},
        {"Diamond", 10, 4},
        {"Pearl", 11, 4},
        {"Platinum", 12, 4},
        {"HeatGold", 7, 4},
        {"SoulSilver", 8, 4},
        {"Ruby", 2, 3},
        {"Sapphire", 1, 3},
        {"Emerald", 3, 3},
        {"FireRed", 4, 2},
        {"LeafGreen", 5, 2},
        {"Colosseum/XD", 15, 3},
        {"Gold", 39, 2},
        {"Silver", 40, 2},
        {"Crystal", 41, 2},
        {"Red", 35, 1},
        {"Blue [INT]/Green [JP]", 36, 1},
        {"Blue [JP]", 37, 1},
        {"Yellow", 38, 1}
    };

    struct Nations {
        int id;
        const char *name;
    };

    static const Nations countryList[122] = {
        {1, "Japan"},
        {8, "Anguilla"},
        {9, "Antigua"},
        {10, "Argentina"},
        {11, "Aruba"},
        {12, "Bahamas"},
        {13, "Barbados"},
        {14, "Belize"},
        {15, "Bolivia"},
        {16, "Brazil"},
        {17, "British Virgin Islands"},
        {18, "Canada"},
        {19, "Cayman Islands"},
        {20, "Chile"},
        {21, "Colombia"},
        {22, "Costa Rica"},
        {23, "Dominica"},
        {24, "Dominican Republic"},
        {25, "Ecuador"},
        {26, "El Salvador"},
        {27, "French Guiana"},
        {28, "Grenada"},
        {29, "Guadeloupe"},
        {30, "Guatemala"},
        {31, "Guyana"},
        {32, "Haiti"},
        {33, "Hounduras"},
        {34, "Jamaica"},
        {35, "Martinique"},
        {36, "Mexico"},
        {37, "Monstserrat"},
        {38, "Netherlands Antilles"},
        {39, "Nicaragua"},
        {40, "Panama"},
        {41, "Paraguay"},
        {42, "Peru"},
        {43, "St. Kitts"},
        {44, "St. Lucia"},
        {45, "St. Vincent & Grenadines"},
        {46, "Suriname"},
        {47, "Trinidad and Tobago"},
        {48, "Turks and Caicos Islands"},
        {49, "United States"},
        {50, "Uruguay"},
        {51, "US Virgin Islands"},
        {52, "Venezuela"},
        {64, "Albania"},
        {65, "Australia"},
        {66, "Austria"},
        {67, "Belgium"},
        {68, "Bosnia and Herzegovina"},
        {69, "Botswana"},
        {70, "Bulgaria"},
        {71, "Croatia"},
        {72, "Cyprus"},
        {73, "Czech Republic"},
        {74, "Denmark"},
        {75, "Estonia"},
        {76, "Finland"},
        {77, "France"},
        {78, "Germany"},
        {79, "Greece"},
        {80, "Hungary"},
        {81, "Iceland"},
        {82, "Ireland"},
        {83, "Italy"},
        {84, "Latvia"},
        {85, "Lesotho"},
        {86, "Liechtenstein"},
        {87, "Lithuania"},
        {88, "Luxembourg"},
        {89, "Macedonia"},
        {90, "Malta"},
        {91, "Montengro"},
        {92, "Mozambique"},
        {93, "Namibia"},
        {94, "Netherlands"},
        {95, "New Zealand"},
        {96, "Norway"},
        {97, "Poland"},
        {98, "Portugal"},
        {99, "Romania"},
        {100, "Russia"},
        {101, "Serbia nad Ksovo"},
        {102, "Slovakia"},
        {103, "Slovenia"},
        {104, "South Africa"},
        {105, "Span"},
        {106, "Swaziland"},
        {107, "Sweden"},
        {108, "Switzerland"},
        {109, "Turkey"},
        {110, "United Kingdom"},
        {111, "Zambia"},
        {112, "Zimbabwe"},
        {113, "Azerbaijan"},
        {114, "Mauritania"},
        {115, "Mali"},
        {116, "Niger"},
        {117, "Chaud"},
        {118, "Sudan"},
        {119, "Eritrea"},
        {120, "Dijibouti"},
        {121, "Somalia"},
        {122, "Andorra"},
        {123, "Gibraltar"},
        {124, "Guernsey"},
        {125, "Isle of Man"},
        {126, "Jersey"},
        {127, "Monaco"},
        {128, "Taiwan"},
        {136, "South Korea"},
        {144, "Hong Kong"},
        {153, "Singapore"},
        {156, "Malayasia"},
        {160, "China"},
        {168, "U.A.E."},
        {169, "India"},
        {174, "Saudi Arabia"},
        {184, "San Marino"},
        {185, "Vatican City"},
        {186, "Bermuda"}
    };

    struct Balls {
        int matchValue;
        const char *name;
        int generationFrom;
    };

    static const Balls ballList[25] = {
        {4, "Poké Ball", 3},
        {3, "Great Ball", 3},
        {2, "Ultra Ball", 3},
        {16, "Cherish Ball", 4},
        {7, "Dive Ball", 3},
        {25, "Dream Ball", 5},
        {13, "Dusk Ball", 4},
        {17, "Fast Ball", 4},
        {22, "Friend Ball", 4},
        {14, "Heal Ball", 4},
        {20, "Heavy Ball", 4},
        {18, "Level Ball", 4},
        {21, "Love Ball", 4},
        {19, "Lure Ball", 4},
        {11, "Luxury Ball", 3},
        {1, "Master Ball", 3},
        {23, "Moon Ball", 4},
        {8, "Nest Ball", 3},
        {6, "Net Ball", 3},
        {12, "Premier Ball", 3},
        {15, "Quick Ball", 4},
        {9, "Repeat Ball", 3},
        {5, "Safari Ball", 3},
        {24, "Sport Ball", 4},
        {10, "Timer Ball", 3}
    };

    extern const int growthTable[100][6];
    static const vector<vector<int>> growthType = {{10, 11, 12, 13, 14, 15, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 37, 38, 41, 42, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 95, 96, 97, 98, 99, 100, 101, 104, 105, 106, 107, 108, 109, 110, 114, 115, 116, 117, 118, 119, 122, 123, 124, 125, 126, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 161, 162, 163, 164, 169, 172, 177, 178, 185, 193, 194, 195, 196, 197, 199, 201, 202, 203, 204, 205, 206, 208, 211, 212, 216, 217, 218, 219, 223, 224, 230, 231, 232, 233, 236, 237, 238, 239, 240, 261, 262, 263, 264, 265, 266, 267, 268, 269, 278, 279, 283, 284, 299, 307, 308, 311, 312, 322, 323, 324, 339, 340, 343, 344, 351, 360, 361, 362, 399, 400, 412, 413, 414, 417, 418, 419, 420, 421, 422, 423, 427, 428, 434, 435, 436, 437, 438, 439, 442, 453, 454, 462, 463, 465, 466, 467, 469, 470, 471, 474, 476, 478, 479, 504, 505, 509, 510, 511, 512, 513, 514, 515, 516, 522, 523, 527, 528, 529, 530, 538, 539, 546, 547, 548, 549, 550, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 580, 581, 585, 586, 587, 588, 589, 590, 591, 592, 593, 595, 596, 597, 598, 605, 606, 613, 614, 615, 616, 617, 618, 621, 622, 623, 624, 625, 626, 631, 632, 659, 660, 664, 665, 666, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 694, 695, 696, 697, 698, 699, 700, 701, 702, 708, 709, 710, 711, 712, 713, 714, 715, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742, 743, 744, 745, 747, 748, 749, 750, 751, 752, 753, 754, 755, 756, 757, 758, 759, 760, 767, 768, 769, 770, 776, 777, 778, 779, 780, 781}, {290, 291, 292, 313, 333, 334, 335, 345, 346, 347, 348, 349, 350, 366, 367, 368, 408, 409, 410, 411, 456, 457}, {285, 286, 296, 297, 314, 316, 317, 320, 321, 336, 341, 342, 425, 426}, {1, 2, 3, 4, 5, 6, 7, 8, 9, 16, 17, 18, 29, 30, 31, 32, 33, 34, 43, 44, 45, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 74, 75, 76, 92, 93, 94, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 179, 180, 181, 182, 186, 187, 188, 189, 191, 192, 198, 207, 213, 215, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 270, 271, 272, 273, 274, 275, 276, 277, 293, 294, 295, 302, 315, 328, 329, 330, 331, 332, 352, 359, 363, 364, 365, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 401, 402, 403, 404, 405, 406, 407, 415, 416, 430, 441, 447, 448, 461, 472, 492, 495, 496, 497, 498, 499, 500, 501, 502, 503, 506, 507, 508, 519, 520, 521, 524, 525, 526, 532, 533, 534, 535, 536, 537, 540, 541, 542, 543, 544, 545, 551, 552, 553, 554, 555, 570, 571, 574, 575, 576, 577, 578, 579, 599, 600, 601, 607, 608, 609, 619, 620, 650, 651, 652, 653, 654, 655, 656, 657, 658, 661, 662, 663, 667, 668, 722, 723, 724, 725, 726, 727, 728, 729, 730, 761, 762, 763, 774}, {35, 36, 39, 40, 113, 165, 166, 167, 168, 173, 174, 175, 176, 183, 184, 190, 200, 209, 210, 222, 225, 235, 242, 298, 300, 301, 303, 325, 326, 327, 337, 338, 353, 354, 355, 356, 358, 370, 424, 429, 431, 432, 433, 440, 468, 477, 517, 518, 531, 572, 573, 594, 707, 746, 764, 771}, {58, 59, 72, 73, 90, 91, 102, 103, 111, 112, 120, 121, 127, 128, 129, 130, 131, 142, 143, 144, 145, 146, 147, 148, 149, 150, 170, 171, 214, 220, 221, 226, 227, 228, 229, 234, 241, 243, 244, 245, 246, 247, 248, 249, 250, 280, 281, 282, 287, 288, 289, 304, 305, 306, 309, 310, 318, 319, 357, 369, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 443, 444, 445, 446, 449, 450, 451, 452, 455, 458, 459, 460, 464, 473, 475, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 493, 494, 582, 583, 584, 602, 603, 604, 610, 611, 612, 627, 628, 629, 630, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 692, 693, 703, 704, 705, 706, 716, 717, 718, 719, 720, 721, 765, 766, 772, 773, 775, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792, 793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805, 806, 807}};;
    static const vector<int> genderCannotChange = {29, 30, 31, 32, 33, 34, 81, 82, 100, 101, 106, 107, 113, 115, 120, 121, 124, 128, 132, 137, 144, 150, 151, 172, 201, 233, 236, 237, 238, 241, 242, 243, 244, 245, 249, 250, 251, 292, 313, 314, 337, 338, 343, 344, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 413, 414, 416, 436, 437, 440, 462, 474, 475, 478, 479, 480, 481, 482, 483, 484, 486, 487, 488, 489, 490, 491, 492, 493, 494, 538, 539, 548, 549, 599, 600, 601, 615, 622, 623, 627, 628, 629, 630, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 669, 670, 671, 703, 716, 717, 718, 719, 720, 721, 758, 761, 762, 763, 772, 773, 774, 781, 785, 786, 787, 788, 789, 790, 791, 792, 793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805, 806, 807};

    struct Icon {
        int identifier;
        const char *description;
    };

    static const Icon iconList[] = {
        {0, "Serena"},
        {1, "Calem"},
        {2, "Sycamore"},
        {3, "Diantha"},
        {4, "Wikstrom"},
        {5, "Malva"},
        {6, "Drasna"},
        {7, "Siebold"},
        {8, "Viola"},
        {9, "Grant"},
        {10, "Korrina"},
        {11, "Ramos"},
        {12, "Clemont"},
        {13, "Valerie"},
        {14, "Olympia"},
        {15, "Wulfric"},
        {16, "Youngster"},
        {17, "Invisible"},
        {18, "Lass"},
        {19, "Lady"},
        {20, "Schoolgirl"},
        {21, "Battle Girl"},
        {22, "Schoolboy"},
        {23, "Rich Boy"},
        {24, "Female Ace Trainer"},
        {26, "Female Ranger"},
        {27, "Male Ace Trainer"},
        {28, "Male Ranger"},
        {29, "Madame"},
        {30, "Monsieur"},
        {31, "Black Belt"},
        {32, "Male Punk"},
        {33, "Fairy Tale Girl"},
        {34, "Shauna"},
        {35, "Tierno"},
        {36, "Trevor"},
        {37, "Brendan"},
        {38, "May"},
        {40, "Hiker"},
        {41, "Aroma Lady"},
        {42, "Male Schoolkid"},
        {43, "Female Schoolkid"},
        {44, "Black Belt"},
        {45, "Battle Girl"},
        {46, "Pokemaniac"},
        {47, "Fairy Tale Girl"},
        {48, "Victor Winstrate"},
        {49, "Victoria Winstrate"},
        {50, "Male Ranger"},
        {51, "Female Ranger"},
        {52, "Male Swimmer"},
        {53, "Hex Maniac"},
        {54, "Male Ace Trainer"},
        {55, "Female Ace Trainer"},
        {56, "Street Thug"},
        {57, "Delinquent"},
        {58, "Male Expert"},
        {59, "Female Expert"},
        {60, "Lady"},
        {61, "Rich Boy"},
        {62, "Ninja Boy"},
        {63, "Beauty"},
        {64, "Guitarist"},
        {65, "Lass"},
        {66, "Male Breeder"},
        {67, "Female Breeder"},
        {68, "Camper"},
        {69, "Picnicker"},
        {70, "Wally"},
        {71, "Steven"},
        {72, "Maxie"},
        {73, "Archie"},
        {128, "Pokémon Center"},
        {129, "Gift"}
    };
}

#endif